### ISSUE TITLE
`tt status` raises error if an application config is not found in Tarantool-based config storage

### ISSUE THREAD

**Issue by p7nov** [tarantool/tt#893] opened 2024-07-05 05:28 UTC
## Steps to reproduce

1. Create a tt environment.
2. Create an application that uses Tarantool-config storage. Find the example `config.yml` [here](https://github.com/tarantool/doc/blob/latest/doc/code_snippets/snippets/centralized_config/instances.enabled/config_storage/config.yaml).
3. Run `tt status`.

## Actual result

```
tt-user@ubuntu-server:~/cluster-integrity$ tt status
   ⨯ can't collect instance information for config_storage: error loading instance "instance001" configuration from config "/home/tt-user/cluster-integrity/instances.enabled/config_storage/config.yaml": error when collecting config from endpoint "tcp://127.0.0.1:4401": a configuration data not found in tarantool for prefix "/myapp/config/"
error when collecting config from endpoint "tcp://127.0.0.1:4402": failed to fetch data from tarantool: builtin/config/storage/init.lua:424: bad storage status: disconnected (LuajitError, code 0x20), see ./tarantool/src/lua/utils.c line 679
error when collecting config from endpoint "tcp://127.0.0.1:4403": a configuration data not found in tarantool for prefix "/myapp/config/"
```

Also, if other applications are present in the environment, their status is not printed. In my case, another app (the config storage) is running in the env at the time of the above call. 

```
tt-user@ubuntu-server:~/cluster-integrity$ tt status tarantool_storage
 INSTANCE                       STATUS   PID   MODE
 tarantool_storage:instance001  RUNNING  7482  RO
 tarantool_storage:instance002  RUNNING  7483  RO
 tarantool_storage:instance003  RUNNING  7484  RW
```

## Expected result

`tt status` successfully prints the `NOT RUNNING` status for the app with absent config and actual statuses of other applications in the environment.

**Comment by oleg-jukovec** [comment] 2024-07-05 05:33
Thank you, but we already have the issue. Duplicate of #732.

**Closed by oleg-jukovec** 2024-07-05 05:33 UTC
