### ISSUE TITLE
Broken 'tt start' output to console

### ISSUE THREAD

**Issue by better0fdead** [tarantool/tt#263] opened 2022-11-28 13:05 UTC
When trying to start an already started instance, console output is broken.
```console
f.terekhin@f-terekhin tt % ./tt start cli/running/test_app/dumb_test_app
   • Starting an instance [cli/running/test_app/dumb_test_app]...
f.terekhin@f-terekhin tt %    ⨯ The Instance is already exists.
./tt stop cli/running/test_app/dumb_test_app 
2022/11/28 16:02:23 The Instance (PID = 92311) has been terminated.
```
OS: macOS 12.6

**Comment by vr009** [comment] 2023-04-17 10:00
I can't reproduce it. Could you provide a reproducer, please. (If the issue is still actual)

**Comment by vr009** [comment] 2023-04-17 12:55
Closing as unreproduceable.

**Closed by vr009** 2023-04-17 12:55 UTC
Labels: bug, teamE, 1sp
